### ISSUE TITLE
Found 156 vulnerabilities (155 low, 1 critical)

### ISSUE THREAD

**Issue by nemanjacosovic** [salesforce-ux/query-ast#8]
Found 156 vulnerabilities (155 low, 1 critical).

<img width="1136" alt="screen shot 2018-08-10 at 12 46 25 pm" src="https://user-images.githubusercontent.com/23336275/43954091-7a278714-9c9b-11e8-93cf-c4a6e15c61fa.png">

This library is used in sass-extract: https://github.com/jgranstrom/sass-extract/

Issue reported in sass-extract as well: https://github.com/jgranstrom/sass-extract/issues/34

**Comment by nemanjacosovic** [comment]
After running npm audit fix I got:
<img width="714" alt="screen shot 2018-08-10 at 12 50 01 pm" src="https://user-images.githubusercontent.com/23336275/43954669-a48e4130-9c9d-11e8-8080-c3efec5d3ce2.png">

**Comment by nemanjacosovic** [comment]
![screen shot 2018-08-10 at 12 51 42 pm](https://user-images.githubusercontent.com/23336275/43954680-b1be9472-9c9d-11e8-8c55-13ab14ec25c5.png)

**Comment by nemanjacosovic** [comment]
![screen shot 2018-08-10 at 12 53 02 pm](https://user-images.githubusercontent.com/23336275/43954707-c3b8a2a8-9c9d-11e8-90f0-1d337dc8b9ef.png)

On the other hand I've updated
invariant 2.2.2 ❯ 2.2.4
jsdoc devDep 3.4.3 ❯ 3.5.5
minami devDep 1.1.1 ❯ 1.2.3

And I will make commit.

**The issue is with scss-parser.**
**There is no GitHub for scss-parser so I've sent an email to NPM security (request 41835).**

**Comment by nemanjacosovic** [comment]
I've also sent a message to salesforce (who are an owner of scss-parser)through online contact form requesting them to update loadsh.

**Comment by nemanjacosovic** [comment]
Unable to push or create pull request.

Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.

**Comment by zahnster** [comment]
I know it's been a while, but thank you for your report.

We have updated all security vulnerabilities and released v1.0.3.
